{
  "version": "10.10.4",
  "status": "approved",
  "html_ids": 548,
  "assets": 13,
  "javascript_files": 10,
  "global_photo_guide": true,
  "guide_available_without_pending_report": true,
  "guide_upload_timeout_seconds": 180,
  "guide_upload_progress": true,
  "optional_sdk_loader_timeout_seconds": 10,
  "firestore_rules": "firestore_26_compacto.rules",
  "storage_rules": "storage_5.rules",
  "service_worker": "sw_47.js",
  "manifest": "manifest_34.json",
  "keyboard_orientation_false_positive_fixed": true,
  "exercise_day_context_locked": true,
  "same_screen_navigation_context_fixed": true,
  "session_delete_confirm_fixed": true,
  "session_edit_full_delete": true,
  "performed_backoff_rows_removable": true
}
