'use strict';
const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const invites=read('modules/v107-invites.js');
const integrity=read('modules/registration-integrity-v10_10_9.js');
const firebaseJson=JSON.parse(read('firebase.json'));
const activeRules=String(firebaseJson?.firestore?.rules||'');
const rules=read(activeRules);
const updater=read('update_v10_10_9.js');
const sw=read('sw.js');
const bridge=read('sw_47.js');
const version=JSON.parse(read('version.json'));
function need(v,m){if(!v)throw new Error(m);}
const appCheck=invites.indexOf('await ensureRegistrationAppCheck()');
const invitePrecheck=invites.indexOf("stage='invite-precheck'");
const pause=invites.indexOf('authListenerSuspended=suspendAuthListenerForRegistration()');
const create=invites.indexOf('auth.createUserWithEmailAndPassword(email,pass)');
const token=invites.indexOf('cred.user.getIdTokenResult(true)');
const transaction=invites.indexOf('async function commitRegistration');
const profileWrite=invites.indexOf("transaction.set(db.collection('users').doc(cred.user.uid),userData)");
const inviteWrite=invites.indexOf("transaction.update(inviteRef,{active:false,usedBy:cred.user.uid");
const resume=invites.indexOf('resumeAuthListenerAfterRegistration(authListenerSuspended)');
const updaterBuild=Number(updater.match(/const CURRENT_BUILD=(\d+)/)?.[1]||0);
const workerBuild=Number(sw.match(/const BUILD_REVISION=(\d+)/)?.[1]||0);
const bridgeBuild=Number(bridge.match(/const BUILD_REVISION=(\d+)/)?.[1]||0);
const workerCache=sw.match(/const CACHE_HOTFIX='([^']+)'/)?.[1]||'';
const bridgeCache=bridge.match(/const CACHE_HOTFIX='([^']+)'/)?.[1]||'';
need(activeRules==='firebase/firestore_28_compacto.rules','Cadastro deve ser validado contra a Rules 28 ativa.');
need(appCheck>=0&&invitePrecheck>appCheck&&create>invitePrecheck,'App Check e convite devem ser validados antes da criação Auth quando o preflight público estiver disponível.');
need(invites.includes('service.getToken(true)'),'O cadastro deve forçar um token App Check válido antes de continuar.');
need(invites.includes("error.code='team-bulls/app-check-failed'"),'Falha de App Check precisa possuir código próprio e não virar permission-denied genérico.');
need(invites.includes("precheckRequiresAuth=true"),'Permission denied no preflight precisa migrar para revalidação autenticada sem consumir o convite.');
need(invites.includes("stage='invite-auth-check'"),'O convite precisa ser revalidado depois do Auth quando a Rules publicada negar o preflight anônimo.');
need(invites.includes("stage='transaction-refresh'"),'Permission denied da transação deve renovar credenciais antes de uma única repetição.');
need(invites.includes("await commitRegistration(inviteRef,cred,userData)"),'A transação protegida deve usar uma função única para evitar divergência entre primeira tentativa e retry.');
need(invites.includes('[REG-FS-403]'),'Permission denied final da transação deve possuir diagnóstico estável REG-FS-403.');
need(invites.includes("window.TeamBullsRegistrationDiagnostics=registrationDiagnostic"),'Diagnóstico seguro da última etapa deve ficar disponível sem expor e-mail, senha ou convite.');
need(pause>=0&&create>pause,'O observador de autenticação deve ser pausado antes de criar a conta Auth.');
need(token>create&&transaction>=0,'A credencial Auth deve ser renovada e a transação canônica deve existir.');
need(invites.includes("tokenResult?.claims?.email||cred.user.email"),'O perfil deve usar o e-mail canônico do token Auth para corresponder literalmente às Rules.');
need(profileWrite>transaction&&inviteWrite>profileWrite,'Perfil e consumo do convite devem permanecer na mesma transação.');
need(resume>profileWrite,'O observador só pode voltar depois da janela crítica do cadastro.');
need(invites.includes("if(typeof AUTH_UNSUBSCRIBE==='function')"),'A pausa precisa usar o unsubscribe já controlado pelo núcleo.');
need(invites.includes("if(typeof startAuthListener==='function')startAuthListener()"),'O observador precisa ser restaurado pelo inicializador oficial.');
need(invites.includes('doRegister.__tbCanonicalInviteRegistration=true'),'O fluxo canônico precisa ser identificado explicitamente.');
need(invites.includes("doRegister.__tbRegistrationPreflight=REGISTRATION_DIAGNOSTIC_REVISION"),'A revisão de preflight deve ser identificável em produção.');
need(invites.includes("REGISTRATION_DIAGNOSTIC_REVISION='preflight2'"),'A revisão resiliente do cadastro precisa estar ativa.');
need(invites.includes("window.addEventListener('team-bulls-runtime-state',enforceCanonicalRegistration)"),'O cadastro seguro deve se restaurar após cada módulo diferido.');
need(!integrity.includes('doRegister=secured'),'A camada de integridade não pode mais substituir doRegister.');
need(integrity.includes("const VERSION='10.10.9-registration2'"),'A revisão passiva da integridade do cadastro precisa estar ativa.');
need(rules.includes('match /studentInvites/{id}'),'As Rules ativas precisam conter a coleção de convites.');
need(rules.includes('allow get: if true;'),'O preflight público deve continuar restrito a get de um convite hash, nunca listagem pública.');
need(rules.includes("getAfter(/databases/$(database)/documents/studentInvites/$(request.resource.data.inviteId)).data.usedBy == uid"),'A criação do aluno deve continuar dependente do convite consumido atomicamente.');
need(rules.includes("getAfter(/databases/$(database)/documents/users/$(request.auth.uid)).data.inviteId == id"),'O consumo do convite deve continuar vinculado ao perfil do mesmo UID.');
// Cadastro depende do runtime, não do feed de anúncios. Durante manual-rescue o feed
// pode ficar deliberadamente abaixo para neutralizar clientes antigos, mas updater e
// os dois workers continuam obrigatoriamente no mesmo build real.
need(updaterBuild>0&&updaterBuild===workerBuild&&workerBuild===bridgeBuild,'Build do cadastro precisa ser idêntico no atualizador e nos dois Service Workers.');
if(version.updateMode==='manual-rescue'){
  need(Number(version.build)>0&&Number(version.build)<=updaterBuild,'Feed manual-rescue não pode anunciar build acima do runtime do cadastro.');
  need(String(version.revision||'').includes('update-loop-kill-switch'),'Feed de resgate não identifica a contenção do atualizador.');
  need(updater.includes('const AUTO_APPLY_SAME_VERSION_HOTFIX=false;'),'Auto-update precisa permanecer suspenso durante o resgate.');
}else need(updaterBuild===version.build,'Build do cadastro precisa coincidir com version.json fora do modo de resgate.');
need(updater.includes("./modules/registration-integrity-v10_10_9.js?v=10.10.9-registration2"),'Atualizador deve renovar explicitamente a integridade do cadastro.');
need(workerCache&&workerCache===bridgeCache,'A release precisa manter os caches coerentes nos dois Service Workers.');
need(sw.includes("./modules/registration-integrity-v10_10_9.js?v=10.10.9-registration2")&&bridge.includes("./modules/registration-integrity-v10_10_9.js?v=10.10.9-registration2"),'Service Workers não podem preparar a revisão registration1 antiga.');
console.log(`APROVADO: cadastro por convite, fallback autenticado, retry único, App Check, atomicidade e runtime ${updaterBuild} seguem coerentes sob ${activeRules}; feed ${version.build}.`);
