'use strict';
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const read=name=>fs.readFileSync(path.join(root,name),'utf8');
function assert(condition,message){if(!condition)throw new Error(message);}

const html=read('index.html');
const core=read('app_v10_10_9_core.js');
const updater=read('update_v10_10_9.js');
const worker=read('sw.js');
const bridge=read('sw_47.js');
const manifest=JSON.parse(read('manifest.json'));
const version=JSON.parse(read('version.json'));

assert(version.version==='10.10.9','version.json incorreto');
assert(version.build===2026082401,'version.json não informa o build atual');
assert(manifest.start_url==='./index.html','start_url ainda está preso a uma versão antiga');
assert(manifest.scope==='./','scope do manifesto incorreto');
assert(html.includes('update_v10_10_9.js?v=10.10.9'),'gerenciador de atualização não é carregado');
assert(html.includes('manifest.json?v=10.10.9'),'manifesto estável não é utilizado');
assert(html.includes('modules/v107-core.js?v=10.10.9'),'módulos estáveis não possuem bust de versão');
assert(!core.includes("serviceWorker.register('sw_47.js'"),'núcleo ainda registra o worker obsoleto');
assert(updater.includes('const CURRENT_BUILD=2026082401'),'atualizador não conhece o build atual');
assert(updater.includes('navigator.serviceWorker.register(`./sw.js?v=${encodeURIComponent(CURRENT_VERSION)}&b=${CURRENT_BUILD}`'),'worker estável não é registrado com build');
assert(updater.includes("fetch(`${VERSION_URL}?t=${Date.now()}`"),'verificação de versão não evita cache HTTP');
assert(updater.includes('sessionStorage.setItem(UPDATE_RELOAD_KEY,releaseKey(target))'),'recarga de atualização não grava versão + build');
assert(updater.includes('function compareRelease(info)'),'atualizador não compara versão + build');
assert(updater.includes('function safeForAutomaticHotfix()'),'hotfix automático não possui gate de tela segura');
assert(updater.includes("if(screen!=='screen-auth')return false"),'hotfix poderia recarregar durante uso ativo');
assert(updater.includes("TB?.flushDrafts?.()"),'rascunhos não são salvos antes da atualização');
assert(updater.includes("manualCheck:()=>checkForUpdates"),'verificação manual não está exposta');
assert(worker.includes("const APP_VERSION='10.10.9'"),'versão do Service Worker incorreta');
assert(worker.includes('const BUILD_REVISION=2026082401'),'Service Worker não anuncia build');
assert(worker.includes("request.mode==='navigate'"),'navegação não é interceptada');
assert(worker.includes('navigationCacheFirst(request,event)'),'navegação não abre imediatamente pelo cache');
assert(worker.includes('event.waitUntil(refreshNavigation(request,event,fallback))'),'HTML não é atualizado em segundo plano após abrir pelo cache');
assert(!worker.includes('navigationNetworkFirst(request,event)'),'navegação voltou a esperar a rede antes de abrir');
assert(worker.includes("relativePath==='/version.json'"),'version.json não recebe estratégia fresca');
const versionedRoute=worker.indexOf("if(VERSIONED_PATH_PATTERN.test(fileName)||url.searchParams.has('v'))");
const mutableRoute=worker.indexOf('if(MUTABLE_PATHS.has(relativePath))');
assert(versionedRoute>=0&&mutableRoute>=0&&versionedRoute<mutableRoute,'recursos versionados não priorizam o cache');
assert(worker.includes("await self.clients.claim()"),'novo worker não assume clientes');
assert(worker.includes("await self.skipWaiting()"),'novo worker não ativa imediatamente');
assert(worker.includes("key!==AUDIO_CACHE_NAME"),'limpeza de cache pode apagar áudio desnecessariamente');
assert(worker.includes("type:'TEAM_BULLS_SW_ACTIVATED',version:APP_VERSION,build:BUILD_REVISION"),'worker não comunica o build ativado');
assert(bridge.includes('ponte de migração'),'ponte para instalações v10.10.4 ausente');
assert(bridge.replace('ponte de migração para instalações controladas pelo antigo sw_47.js','Service Worker estável e atualização sem reinstalação')===worker,'ponte e worker principal divergiram');
console.log('APROVADO: atualização build-aware, manifesto estável, cache-first e ponte legada validados.');
